export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';

export const FETCHING_PRODUCT = 'FETCHING_PRODUCT';
export const FETCHING_PRODUCT_SUCCESS = 'FETCHING_PRODUCT_SUCCESS';
export const FETCHING_PRODUCT_FAILURE = 'FETCHING_PRODUCT_FAILURE';

export const SET_MESSAGE = 'SET_MESSAGE';
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE';
export const CLEAR_ERROR_MESSAGE = 'CLEAR_ERROR_MESSAGE';
export const UPDATED_MESSAGE = 'UPDATED_MESSAGE';
export const CLEAR_UPDATED_MESSAGE = 'CLEAR_UPDATED_MESSAGE'; 

export const FETCHING_CART = 'FETCHING_CART';
export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS';
export const FETCHING_CART_SUCCESS = 'FETCHING_CART_SUCCESS';
export const FETCHING_CART_FAILURE = 'FETCHING_CART_FAILURE';
export const PAY_TOTAL_FAILURE = 'PAY_TOTAL_FAILURE';
export const PAID_TOTAL_SUCCESSFULLY = 'PAID_TOTAL_SUCCESSFULLY';

export const UPDATE_REVIEW_BODY = 'UPDATE_REVIEW_BODY';
export const UPDATE_REVIEW_RATING = 'UPDATE_REVIEW_RATING';
export const SUBMISSION_REVIEW_SUCCESS = 'SUBMISSION_REVIEW_SUCCESS';
export const SUBMISSION_EREVIEW_ERROR = 'SUBMISSION_EREVIEW_ERROR';
export const DELETION_REVIEW_SUCCESS = 'DELETION_REVIEW_SUCCESS';
export const DELETION_REVIEW_ERROR = 'DELETION_REVIEW_ERROR';

export const FETCHING_RECEIPTS = 'FETCHING_RECEIPTS';
export const FETCHING_RECEIPTS_SUCCESS = 'FETCHING_RECEIPTS_SUCCESS';
export const FETCHING_RECEIPTS_FAILURE = 'FETCHING_RECEIPTS_FAILURE';

export const FETCHING_PURCHASED_PRODUCT = 'FETCHING_PURCHASED_PRODUCT';
export const FETCHING_PURCHASED_PRODUCT_SUCCESS = 'FETCHING_PURCHASED_PRODUCT_SUCCESS';
export const FETCHING_PURCHASED_PRODUCT_FAILURE = 'FETCHING_PURCHASED_PRODUCT_FAILURE';

export const UPDATE_YOUR_EMAIL = 'UPDATE_YOUR_EMAIL';
export const YOUR_EMAIL_ERROR = 'YOUR_EMAIL_ERROR';
export const RESET_PASS_SUCCESS = 'RESET_PASS_SUCCESS';
export const RESET_PASS_FAILURE = 'RESET_PASS_FAILURE';

export const UPDATE_ACCOUNT_FIRST_NAME = 'UPDATE_ACCOUNT_FIRST_NAME';
export const UPDATE_ACCOUNT_LAST_NAME = 'UPDATE_ACCOUNT_LAST_NAME';
export const UPDATE_ACCOUNT_EMAIL = 'UPDATE_ACCOUNT_EMAIL';

export const ACCOUNT_FIRST_NAME_ERROR = 'ACCOUNT_FIRST_NAME_ERROR';
export const ACCOUNT_LAST_NAME_ERROR = 'ACCOUNT_LAST_NAME_ERROR';
export const ACCOUNT_EMAIL_ERROR = 'ACCOUNT_EMAIL_ERROR';

export const FETCHING_ACCOUNT_USER = 'FETCHING_ACCOUNT_USER';
export const FETCHING_ACCOUNT_USER_SUCCESS = 'FETCHING_ACCOUNT_USER_SUCCESS';
export const FETCHING_ACCOUNT_USER_FAILURE = 'FETCHING_ACCOUNT_USER_FAILURE';

